### ISSUE TITLE
Layout umsetzen

### ISSUE THREAD

**Issue by IngaF** [IngaF/ProjektC#1]
Das ausgesuchte Layout soll in Dart umgesetzt werden. Vielleicht auch erstmal mehr oder weniger als Grundgerüst.

1. Login-Seite/ Registrieren
2. Profil
3. Galerie
4. Statistik/Tipps
5. Upload

**Comment by IngaF** [comment]
Ich fange hier schon mal an!

**Comment by IngaF** [comment]
Layout: Login-Screen ohne Funktionalitäten

**Comment by KhatiaM** [comment]
search Bar erstmal ohne Funktion

**Comment by IngaF** [comment]
- weitere Profil-Elemente hinzugefügt (siehe Commit)
- @KhatiaM :  nicht wundern, ich musste deinen Code (zur Suche?) auskommentieren, da er Fehler ausgeworfen hat

**Comment by IngaF** [comment]
2. Profil-Layout fertig --> noch keine Funktionen
Als nächstes würde ich Nr.3 (Galerie) machen

**Comment by IngaF** [comment]
3. Galerie: Verknüpfung mit BottomNavBar --> Layout noch nicht fertig

**Comment by IngaF** [comment]
3. Layout für die Galerie --> AppBar mit den auswählbaren Ländern --> ohne Funktion

Ich mache dann weiter mit dem Layout für  4. Statistik/Tipps.

**Comment by IngaF** [comment]
-AppBar mit ProfilBild, Name und Logo --> damit man immer Überblick über sein Profil hat
- Struktur für Reisetipps: Unter der AppBarNav als Toggle-Container anzeigen lassen?

**Comment by IngaF** [comment]
4. Die Reisetipps erscheinen jetzt als Toggle-Container unter der AppBar. Vielleicht Statistik einfach weglassen? Eine neue Seite dafür erscheint mir irgendwie zuungunsten der Benutzerführung zu laufen. 

**ToDo:** Unbedingt noch die Scrollbarkeit der Galerie beheben. Im Moment wird nur der Galeriecontainer gescrollt. Besser wäre, die ganze Seite scrollen zu können!

**Comment by KhatiaM** [comment]
Statistiken kann man weg lasen sonst wir unübersichtlich. 
Ich überlege  search button  von Profil weg zu lassen über Menü  Bar finde ich besser.

**Comment by IngaF** [comment]
Hmm... also gerade bei der Suche finde ich es besser, wenn man den Button auf den Blick sehen kann. Also von der Usability her ist es auf jeden Fall intuitiver...

**Comment by IngaF** [comment]
- Reisetipps sind erstmal wieder ausgeblendet --> dafür überleg ich mir was anderes
- Bilder in der Galerie sind nun klickbar --> es öffnet sich ein neues Fenster mit Bild-Infos und Beschreibungen, die muss dann nur noch durch Inhalt der DB ausgetauscht werden

**Comment by IngaF** [comment]
5. Upload-Layout
- Page ist mit Menü verknüpft
- Upload-Form als Grundgerüst, soll später aufgerufen werden, wenn ein Bild ausgesucht/gemacht wurde
- ButtomNavBar eingefügt --> linker Button = Funktion zum Auswahl eines Bildes vom Handy
TODO: - ButtomNavBar --> rechter Button = Funktion zum Öffnen der HandyKamera

**Comment by IngaF** [comment]
In der ButtomNavBar ist jetzt auch eine Klasse zum benutzen der Handykamera erstellt.
ToDo: Layout und Formatierung der Elemente fehlt noch!

**Comment by IngaF** [comment]
- Layout für Bildauswahl (Kamera und Galerie) fertig, Upload-Formular als Grundgerüst

**Comment by KhatiaM** [comment]
Suchergebnis Darstellung  anpassen -> anordnung, Scroll.

**Comment by KhatiaM** [comment]
Start page ->register button hinzufügen 
Register Page -> user Daten zum eintragen (Name ,Nachname,Heimatstadt)
