### ISSUE TITLE
Datenbank-Recherche

### ISSUE THREAD

**Issue by IngaF** [IngaF/ProjektC#2]
Welche Möglichkeiten und Plattformen gibt es? 
NoSQL-Datenbank, also nicht-relational oder relational oder die alte Datenbank weiter benutzen?

**Comment by IngaF** [comment]
Eine NoSQL-Variante für Flutter wäre [Firebase](https://firebase.google.com/). Dort gibt es auch die Möglichkeit einen Free-Account anzulegen.

**Comment by KhatiaM** [comment]
Ich mache mich schlau über  firebase habe noch nie damit beschäftigt, aber scheint ganz  gut zu sein

**Comment by IngaF** [comment]
Da die neue Datenbank ja anders aufgebaut ist, als die alte Relationale, sollten wir uns vielleicht vorher nochmal ein paar Gedanken um die Struktur machen.  Vielleicht mit einem Entity Relationship Diagram?

**Comment by IngaF** [comment]
- Datenbankdesign-Entwurf: Versuch der Strukturierung der Daten, da es keine Joins gibt, sollen alle Daten mit einer Abfrage aufrufbar sein

**Comment by IngaF** [comment]
Wir müssten uns dann auch entscheiden, welche Datenbank wir nutzen wollen, also entweder die **Realtime Database**  oder **Cloud Firestore**. Ich habe mich mal ein bisschen belesen und finde die Cloud Firestore eigentlich am sinnvollsten für unser Projekt. 

Der Vorteil im Gegensatz zur Realtime Database ist, dass man die Daten in Docuemnts und Subcollections speichern kann, man kann also komplexere, hierárchische Strukturen verarbeiten. Außerdem ist der Aufwand für die Denormalisierung wesentlich  geringer als bei der Realtime Database. Bei der Cloud Firestore ist auch die Kombination von Sortieren UND Filtern in einer Abfrage möglich, wohingegen die Realtime Database entweder sortieren ODER filtern kann. Und man kann auch nur Abfragen in Subcollections stellen und nicht nur in einer Collection. 

Insgesamt wäre ich also für die **Cloud Firestore**. Hier nochmal ein Link zum Data Model : https://firebase.google.com/docs/firestore/data-model
Hast du dir den Datenbank-Entwurf von mir schon angesehen?

Ich würde jetzt weitermachen und mal recherchieren wie man die Bilder (die man ja auch dort hochladen und verwalten kann) mit der Datenbank verknüpfen kann und wie die User-Authentification funktioniert.

**Comment by KhatiaM** [comment]
Ja habe ich gesehen.
Können wir gerne machen ich bin immer noch am recherchieren  Daten
speichern /aufrufen . (User login  da hätte  ich schon eine Idee )
Ein anderes Problem  ist bei mir aufgetaucht,irgendwie android  Simulator
läuft  garnicht bei mir,daher  mache ich mit iPhone  Simulator weiter.

IngaF <notifications@github.com> schrieb am Fr., 10. Mai 2019, 09:39:

**Comment by IngaF** [comment]
**1. Bilder:** Die Bilder werden im Storage der Firebase gespeichert und die URL vom Foto wird wiederum in einem Feld der entsprechenden Sammlung der Cloud Firestore gespeichert. Also vom Prinzip her genau wie in der MySQL-DB auch, nur, dass die Bilder nicht lokal sondern in der Cloud liegen.
 
**2. User-Authentication:** Die Umsetzung des Logins und der Registrierung ist ja Gott sei Dank ziemlich easy, weil man das ja bequem mit der Firebase Authentication machen kann und alle Einstellungen direkt dort vornehmen kann. Um die angemeldeten User mit der Cloud Firestore zu verknüpfen, muss die User-UID mit der Dokument-ID in der Sammlung übereinstimmen. 
![authentication](https://user-images.githubusercontent.com/14993571/57581982-aeb23180-74bf-11e9-8fd0-3c11476694ea.jpg)

**3. Emulator:** Kommt es nicht zu Problemen, wenn wir unterschiedliche Emulatoren verwenden? Bzw. gibt es bei iOS nicht andere Methoden, als bei Android, sodass der gleiche Code nicht auf beiden Geräten funktioniert? Bis jetzt haben wir ja quasi fast nur das Layout geschrieben, aber ich hab bedenken, dass wenn wir jetzt anfangen die richtigen Funktionen zu programmieren, es bei uns dann nicht einheitlich funktioniert. Oder ist das unproblematisch?
