### ISSUE TITLE
Worldmap

### ISSUE THREAD

**Issue by IngaF** [IngaF/ProjektC#4]
Überlegen, wie die Weltkarte umgesetzt werden soll und ob es sinnvoll ist, die klickbare Weltkarte aus dem letzten Projekt weiter zu benutzen. Möglicherweise ist die Weltkarte auf einem kleinen Bildschirm nicht mehr besonders benutzerfreundlich und es muss sich eine Alternative (vielleicht als Drop-Down-Menü?) überlegt werden.

Anschließend umsetzen!

**Comment by KhatiaM** [comment]
ja dieser Überlegung hatte ich auch .Dropdown Menu wäre praktisch

**Comment by IngaF** [comment]
Ich habe als Worldmap-Alternative eine BottomNavBar ausprobiert. Im Moment ist die Bar allerdings noch nicht verlinkt. Die ist wieder in Kontinente aufgeteilt. Beim Tap auf einen Kontinent gelangt man auf die Galerie-Seite und dort könnte man dann das Land auswählen. Das wäre jetzt mein Vorschlag.
