### ISSUE TITLE
Muster/Strukturierung

### ISSUE THREAD

**Issue by IngaF** [IngaF/ProjektC#8]
Ich habe mich heute nocheinmal mit der Strukturierung beschäftigt. Dabei bin ich auf das BLoC-Pattern gestoßen, was mir einfacher zu sein scheint als das MVC-Muster. Hier ein gutes Tutorial dazu: https://www.youtube.com/watch?v=oxeYeMHVLII
Vielleicht nehmen wir lieber das, statt MVC?

**Comment by KhatiaM** [comment]
finde ich gut habe angefangen user login nach BLOC zu machen
