### ISSUE TITLE
Content mit Datenbank verknüpfen

### ISSUE THREAD

**Issue by IngaF** [IngaF/ProjektC#9]
Der gesamte Content aller Screens inklusive Bilder, insbesondere Kontinente, Länder und Galerien, müssen mit der DB verknüpft werden.

**Comment by IngaF** [comment]
- Profilseite fertig verbunden --> wenn die Authentifizierung fertig ist, muss noch der CurrentUser ergänzt werden
next ToDo: ProfilObenRow(), Kontinente der BottomNavigationBarItems

**Comment by IngaF** [comment]
- ProfilObenRow() ist nun mit DB verknüpft
- in den  BottomNavBarItems werden nun die hinterlegten Kontinente der User angezeigt

ToDo: - anzeigen der Galerie im body
- auslesen und anzeigen der jeweiligen Länder in den Tabs des AppBar Bottom

**Comment by IngaF** [comment]
- die Galerien sind wieder mit den jeweiligen Tabs verknüpft
- der angeklickte Kontinent wird als String an die Galerie übergeben

ToDo: 
- Query für das Auslesen der Länder der angeklickten Kontinente --> darstellen als Tabs in der AppBar
- Query der hinterlegten Bilder --> darstellen in der Galerie

**Comment by IngaF** [comment]
- Query für Länder + Fotos gebaut
- Kontinent-String an Query getLandData() übergeben --> Länder der Kontinente werden angezeigt
- Tabs werden aus der ausgelesenen laenderList[] erzeugt

ToDo: onTap()-Event übergibt Land an Galerie und liest alle Bilder + Infos aus DB aus

**Comment by IngaF** [comment]
- erzeugen von Tabs und TabViews abhängig von der Anzahl der Länder aus der DB
- übergeben des angeklickten Landes an die Galerie

ToDo: - StreamBuilder für Foto-URLs und Fotoinfos aus der DB

**Comment by IngaF** [comment]
- Fotos des jeweiligen Landes werden in der Galerie angezeigt --> bei Klick-Event
ToDos:
- Bug: der dritte Tab jeder Ansicht zeigt keine SingleFoto-Ansicht der Fotos
- Bug: index-Error bei Kontinenten, die nur ein Land hinterlegt haben, z.B. Australien
- Name des Landes soll auch beim wischen nach links oder rechts übergeben werden

**Comment by IngaF** [comment]
- Fotos werden jetzt auch direkt beim Klick auf den Kontinent angezeigt
- Name des Landes wird jetzt auch beim Swipen und Klicken an die Galerie übergeben
ToDo: 
- Bug: SingleFoto-Ansicht funktioniert immer beim letzten Land im Loop nicht
- Bug: index-Error bei nur einem angezeigtem Land, also bei index 0

**Comment by KhatiaM** [comment]
Error beim  click auf Kontinenten die  Bilder werden nicht angezeigt

**Comment by IngaF** [comment]
Da wäre ja ein Screenshot nicht schlecht.  Bei mir funktioniert es nämlich.

**Comment by KhatiaM** [comment]
Schon erledigt 
Problem lag an TabController . 
Datei -> Gallery.dart  
line 29 -> controller = TabController(vsync: NavigatorState(), length:20);

**Comment by IngaF** [comment]
Und was war da genau das Problem? Weil bei mir hat er keinen Error geworfen.

**Comment by KhatiaM** [comment]
Das es in controller 20 stand und 3 Tabs waren tabview war nicht möglich
und  hat error geworfen

IngaF <notifications@github.com> schrieb am Fr., 14. Juni 2019, 20:09:

**Comment by IngaF** [comment]
Einfach eine andere Zahl eintragen löst ja das Problem nicht, weil die Tabs dynamisch sind und immer unterschiedlich lang, je nachdem wie viele Länder in der DB hinterlegt sind. Europa hat z.B. momentan 4 Tabs, weil es vier Länder sind.

Ich überleg mir dazu was. Solche Infos kannst du ruhig gleich dazu schreiben, dann hat man das besser im Blick.

**Comment by KhatiaM** [comment]
Ja das ist klar.
 Das Problem ist bei Kontinenten aufgetreten bei Länder funktioniert.

IngaF <notifications@github.com> schrieb am Fr., 14. Juni 2019, 22:02:

**Comment by IngaF** [comment]
Dann verstehe ich es jetzt noch weniger, wenn du sagst, dass das Problem in der gallery.dart auftrat, aber die Tabs der Kontinente betrifft. Weil die Tabs der Kontinente nämlich in der profil.dart in der ButtonNavigationBar definiert sind. Und die hat auch gar keinen TabController....

**Comment by IngaF** [comment]
Sollte das Problem mit dem Error in der Galerie immer noch auftreten, bitte ich dich um einen Screenshot der Fehlermeldung... 

- die richtige Anzahl der Länder aus der DB werden nun im Profil angezeigt (dazu wird, wenn ein neues Land vom User hochgeladen wird (upload.dart), die aktuelle Anzahl ausgelesen, um eins addiert und die Zahl geupdated)

ToDo: 
- richtige Anzahl der Fotos aus DB einbinden

**Comment by IngaF** [comment]
Da ich keine Fehlermeldung von dir zur Verfügung hatte, habe ich versucht den TabController-Bug so zu fixen: 
- TabAnzahl wird nun von einem übergeordneten Widget an die Galerie übergeben
- es gibt noch Probleme beim controller.index, daher werden die unterschiedlichen Länder-Tabs mometan nicht angezeigt ... tbc

ToDo:
- controller.index fixen
- richtige Anzahl der Fotos aus DB einbinden (evtl. mit collectionGroup queries)

**Comment by IngaF** [comment]
- controller.index-Bug ist gefixt
- richtige Anzahl der Fotos wird in der Profilansicht angezeigt

ToDo:
- @KhatiaM : bitte prüfen, ob der Error im TabController bei dir immer noch auftritt. Da ich keinen Screenshot von dir bekommen habe, konnte ich es nicht wirklich testen.

**Comment by IngaF** [comment]
- Bug-Fix in TabController: es wird kein Fehler mehr geworfen, wenn die Anzahl der Tabs innerhalb eines Kontinents größer ist, als die Anzahl der Tabs im nächsten angeklickten Kontinent

**Comment by IngaF** [comment]
- Bug-Fix: Error beim Anklicken der Fotos im jeweils letzten Tab im Kontinent behoben
- SingleFoto-Layout optimiert

**Comment by IngaF** [comment]
- Land und Ort in der SinglePhoto-Ansicht hinzugefügt + entsprechendes Feld in der DB ergänzt + entsprechendes Feld beim Upload gesetzt

**Comment by KhatiaM** [comment]
Anmeldung noch nicht komplett.
Error nach dem Anmeldung im Bereich Länder/Kontinente.
Registration ergänzen .

**Comment by IngaF** [comment]
Du hast es ja jetzt in mein Thema geschrieben... Ein eigenes Issue dafür wäre schon besser. Ich habe das Issue hier noch nicht geschlossen, da immer noch dein Feedback/Screenshot bezüglich des Fehlers in den Tabs fehlt. Sonst kommen wir hier durcheinander...

**Comment by IngaF** [comment]
Für den Fall, dass noch keine Fotos bzw. keine Kontinente angelegt sind (z.B. bei neuer Registrierung), wird in der BottomNavigationBar die Klasse NoGallery( ) aufgerufen. Hier wird der User informiert, dass noch keine Fotos hochgeladen wurden, außerdem gibt es einen Link zum Upload.

@KhatiaM  Ich habe bei deinem neu angelegten Benutzer in der Datenbank: **/Nutzer/ALVkjOQXyVfa2qpHVWZNY1ayipA3/Kontinent/LhBoY4wsEvQw8iPKaLP9**
noch das Feld "name" hinzugefügt. Der Name des Kontinents erscheint als Tabname in der BottomNavigationBar. Steht dort nichts, wirft das Programm einen Error. 
Außerdem fehlt mir noch die Info, ob die Länder in der Galerie immer noch einen Fehler bei dir werfen... siehe hier: https://github.com/IngaF/ProjektC/issues/9#issuecomment-502050282

**Comment by KhatiaM** [comment]
Genau das ist das problem  bei andere Nutzer gibt's  kein error .
Tab controller  funktioniert kein fehler.

**Comment by IngaF** [comment]
Dann ist das Thema jetzt abgeschlossen.
